services:
  postgres:
    image: postgres:17
    container_name: bun-auth-postgres
    environment:
      POSTGRES_DB: bun-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
